### add data to storage

POST http://localhost:3003/get-products
Content-Type: application/json

{ "productName": "Name",
    "productURL": "https://url.com",
    "productPrice": "999",
    "platform": "xyz" } 

### get data

GET  http://localhost:3003/get-products
Content-Type: application/json